@startuml
annotation java.lang.Override
class Circle
class Rectangle
class Shape
class ShapeMain
class java.util.Scanner
Circle ..> java.lang.Override
Circle --|> Shape
Rectangle ..> java.lang.Override
Rectangle --|> Shape
ShapeMain ..> java.util.Scanner
@enduml